name: 'Create CED version'
description: 'Github action to create an empty version within a CloudEdgeDistribution project'
inputs:
  cli-token:
    description: 'CloudEdgeDistribution CLI token'
    required: true
  environment:
    description: 'Environment to use in CloudEdgeDistribution, it'll use the default environment in ced.json if it isn't specified.'
    required: false
  path:
    description: 'Path to the CloudEdgeDistribution project, default is current folder.'
    required: false
outputs:
  version: 
    description: 'Created version name'
runs:
  using: 'node12'
  main: 'lib/index.js'